//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contact_App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contact_App.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Profile.
        /// </summary>
        internal static string AddProfileTitlePage {
            get {
                return ResourceManager.GetString("AddProfileTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName and Name fields must be filled.
        /// </summary>
        internal static string AlertAddEditProfile {
            get {
                return ResourceManager.GetString("AlertAddEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!! Account created.
        /// </summary>
        internal static string AuthenticationSuccess {
            get {
                return ResourceManager.GetString("AuthenticationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #000000.
        /// </summary>
        internal static string BlackTextColor {
            get {
                return ResourceManager.GetString("BlackTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;#696969&quot;.
        /// </summary>
        internal static string ButtonBorderColor {
            get {
                return ResourceManager.GetString("ButtonBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ButtonBorderValue {
            get {
                return ResourceManager.GetString("ButtonBorderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;#D2691E&quot;.
        /// </summary>
        internal static string ButtonColor {
            get {
                return ResourceManager.GetString("ButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ConfirmCancel {
            get {
                return ResourceManager.GetString("ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ConfirmOK {
            get {
                return ResourceManager.GetString("ConfirmOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmPasswordText {
            get {
                return ResourceManager.GetString("ConfirmPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteContextAction {
            get {
                return ResourceManager.GetString("DeleteContextAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you really want to delete this profile?.
        /// </summary>
        internal static string DeleteProfileQuestion {
            get {
                return ResourceManager.GetString("DeleteProfileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditContextAction {
            get {
                return ResourceManager.GetString("EditContextAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string EditProfileTitlePage {
            get {
                return ResourceManager.GetString("EditProfileTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose action.
        /// </summary>
        internal static string ImageProfileAction {
            get {
                return ResourceManager.GetString("ImageProfileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login. Login must be from 4 to 16 characters and must not start with a number.
        /// </summary>
        internal static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password!.
        /// </summary>
        internal static string InvalidLoginOrPassword {
            get {
                return ResourceManager.GetString("InvalidLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password!.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort list by.
        /// </summary>
        internal static string LabelSortListBy {
            get {
                return ResourceManager.GetString("LabelSortListBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login is already taken. Come up with another.
        /// </summary>
        internal static string LoginTaken {
            get {
                return ResourceManager.GetString("LoginTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName.
        /// </summary>
        internal static string NicknameText {
            get {
                return ResourceManager.GetString("NicknameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profiles added.
        /// </summary>
        internal static string NoProfilesLabel {
            get {
                return ResourceManager.GetString("NoProfilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords missmatch. Re-enter passwords.
        /// </summary>
        internal static string PasswordMissMatch {
            get {
                return ResourceManager.GetString("PasswordMissMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick at Gallery.
        /// </summary>
        internal static string PickAtGallery {
            get {
                return ResourceManager.GetString("PickAtGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date creation.
        /// </summary>
        internal static string RadioCreation {
            get {
                return ResourceManager.GetString("RadioCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string RadioName {
            get {
                return ResourceManager.GetString("RadioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName.
        /// </summary>
        internal static string RadioNickName {
            get {
                return ResourceManager.GetString("RadioNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        internal static string SignInButtonText {
            get {
                return ResourceManager.GetString("SignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users SignIn.
        /// </summary>
        internal static string SignInTitlePage {
            get {
                return ResourceManager.GetString("SignInTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string SignUpButtonText {
            get {
                return ResourceManager.GetString("SignUpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users SignUp.
        /// </summary>
        internal static string SignUpTitlePage {
            get {
                return ResourceManager.GetString("SignUpTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo with camera.
        /// </summary>
        internal static string TakePhotoWithCamera {
            get {
                return ResourceManager.GetString("TakePhotoWithCamera", resourceCulture);
            }
        }
    }
}
